# -*- coding: utf-8 -*-
"""P1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/136121gPb2NetHm2GJQ8BXlGOIUXM5B0r
"""

import pandas as pd

df = pd.read_csv('EnjoySport.csv',index_col='Example')

df.head()

pos = df[df.EnjoySport == "Yes"].drop(['EnjoySport'],axis=1)

pos.head()

h = ['%','%','%','%','%','%']
print(h)

h = pos.iloc[0].tolist()
print(h)

for i,d in pos.iloc[1:].iterrows():
  for j in range(len(d)):
    if h[j] != d[j]:
      h[j] = '?'
  print(h)

