# -*- coding: utf-8 -*-
"""P7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_hZs3FkNcw2D8Q6cojX8RdEYBhO5q63L
"""

import pandas as pd
import numpy as np
from urllib.request import urlopen

url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.hungarian.data'

names = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'heartdisease']
df = pd.read_csv(urlopen(url), names = names).drop(columns=['ca', 'slope', 'thal','oldpeak']).replace('?', np.nan)

df.head()

!pip3 install pgmpy

from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator

model = BayesianModel([('age', 'trestbps'), ('age', 'fbs'), ('sex', 'trestbps'), ('age', 'chol'), ('sex', 'chol'),('exang', 'trestbps'),('trestbps','heartdisease'),('fbs','heartdisease'),('chol','heartdisease')])

model.fit(df, estimator=MaximumLikelihoodEstimator)

from pgmpy.inference import VariableElimination
ve = VariableElimination(model)

q = ve.query(variables=['heartdisease'], evidence={'age': 28, 'sex':0}, show_progress=False)
print(q)
q = ve.query(variables=['heartdisease'], evidence={'chol': 150,'age': 30, 'sex':1}, show_progress=False)
print(q)

