# -*- coding: utf-8 -*-
"""P9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vm9xJOYtCbV8TdPyeUBX3tUe5gr7UrOj
"""

from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import numpy as np

d=load_iris()

X_train,X_test,y_train,y_test = train_test_split(d.data,d.target,random_state=0)

kn=KNeighborsClassifier(1)
kn.fit(X_train,y_train)

y_pred = [kn.predict([x])[0] for x in X_test]
print('Expected',y_test.tolist())
print('Predicted',y_pred)

kn.score(X_test,y_test)